apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: rnakai/mysql:v1
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-persistent-storage
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
      app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
    targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
