apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  labels:
    app: phpmyadmin
spec:
  containers:
  - name: phpmyadmin
    image: rnakai/phpmyadmin:v1
    imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 5000
    name: phpmyadmin
    protocol: TCP
    targetPort: 5000
    nodePort: 5000
