apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: wordpress
spec:
  containers:
    - name: wordpress
      image: rnakai/wordpress:v1
      imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    name: wordpress
    protocol: TCP
    targetPort: 5050
    nodePort: 5050
