apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: rnakai/ftps:v1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector:
    app: ftps
  ports:
  - name: ftps-data
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
    nodePort: 21
  - name: pasv-min
    protocol: TCP
    port: 30020
    targetPort: 30020
  - name: pasv-max
    protocol: TCP
    port: 30021
    targetPort: 30021
